spring:
  application:
    name: AIProjectManager

  datasource:
    url: jdbc:postgresql://localhost:5432/pmbot
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

yougile:
  base-url: https://yougile.com/api-v2
